[server]
port = 8501
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
baseUrlPath = ""
allowRunOnSave = true

[browser]
gatherUsageStats = false
serverAddress = "192.168.25.14"
serverPort = 8501

[global]
developmentMode = false